# Debugging the config:
# - resticprofile default.show
# - resticprofile truenas.show
# - resticprofile rsync-net.show

# Debugging a command:
# - resticprofile --dry-run truenas.backup

# Debugging a backup:
# - resticprofile truenas.backup --dry-run
#   Note: you can append restic flags *but* some aren't passed through; run
#   resticprofile with --dry-run to check that the restic command actually has
#   all the flags.

# Backup failed with `Fatal: repository does not exist`? There's a high chance
# that the hostname reported by MacOS has changed, e.g. from `mac.lan` to
# `Johns-MacBook-Air-2022.local`. sftp restic-backups-to-truenas, check if the
# directory exists, and `ln -s old new` if not.

# Backup:
# - resticprofile truenas.backup

# Initial setup:
# - ssh-keygen -t rsa -b 4096 -o -N '' -q \
#     -f "${HOME}/.ssh/keys/restic-backups-to-truenas" \
#     -C "restic-backups-to-truenas"
# - ssh-keygen -t rsa -b 4096 -o -N '' -q \
#     -f "${HOME}/.ssh/keys/restic-backups-to-rsync-net" \
#     -C "restic-backups-to-rsync-net"
# - Add to authorized_keys: command="internal-sftp",restrict,no-port-forwarding,no-x11-forwarding,no-agent-forwarding PUBLIC KEY
# - ssh config configures the identity file.
# - resticprofile generate --random-key \
#     > ${HOME}/.config/backups/restic-password
# - resticprofile truenas.init
# - resticprofile rsync-net.init
# - Check what would be transferred:
#   - Get the restic command by running:
#     resticprofile --dry-run truenas-hosting.backup
#   - Add `--dry-run -vv` to the command.

[default]
  password-file = "{{ .Env.HOME }}/.config/backups/restic-password"

  [default.backup]
    source = ["{{ .Env.HOME }}"]
    one-file-system = true
    exclude-caches = true
    exclude-larger-than = "1G"
    exclude-file = [
        "{{ .Env.HOME }}/.gitignore.global",
        "{{ .Env.HOME }}/.config/backups/excludes",
    ]

  [default.retention]
    keep-last = 5
    keep-daily = 7
    keep-weekly = 4
    keep-monthly = 12

[truenas]
inherit = "default"
repository = "sftp:restic-backups-to-truenas:restic/{{ .Env.USER }}-{{ .Hostname }}"

[rsync-net]
inherit = "default"
repository = "sftp:restic-backups-to-rsync-net:restic/{{ .Env.USER }}-{{ .Hostname }}"

[truenas-hosting]
inherit = "truenas"
  [truenas-hosting.backup]
    source = ["{{ .Env.HOME }}", "/var/www/sites"]

[rsync-net-hosting]
inherit = "rsync-net"
  [rsync-net-hosting.backup]
    source = ["{{ .Env.HOME }}", "/var/www/sites"]
