#!/usr/bin/env -S "populate_pre_commit"
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # managed-by-populate-pre-commit start: conventional-pre-commit.yaml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
    - id: conventional-pre-commit
      stages:
      - commit-msg
      args:
      - --verbose
  # managed-by-populate-pre-commit end: conventional-pre-commit.yaml
  # managed-by-populate-pre-commit start: hooks.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-vcs-permalinks
  # managed-by-populate-pre-commit end: hooks.yaml
  # managed-by-populate-pre-commit start: keep-sorted.yaml
  - repo: https://github.com/google/keep-sorted
    rev: v0.8.0
    hooks:
    - id: keep-sorted
  # managed-by-populate-pre-commit end: keep-sorted.yaml
  # managed-by-populate-pre-commit start: meta.yaml
  - repo: meta
    hooks:
    - id: check-hooks-apply
  # managed-by-populate-pre-commit end: meta.yaml
  # managed-by-populate-pre-commit start: shellcheck.yaml
  - repo: local
    hooks:
    - id: shellcheck
      name: Run `shellcheck`
      language: system
      types:
      - shell
      entry: shellcheck -e SC1090 -e SC1091
  # managed-by-populate-pre-commit end: shellcheck.yaml
  # managed-by-populate-pre-commit start: spellcheck.yaml
  - repo: local
    hooks:
    - id: spellcheck
      stages:
      - commit-msg
      name: Check spelling
      language: system
      verbose: true
      entry: spell-check-wrapper
  # managed-by-populate-pre-commit end: spellcheck.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      # keep-sorted start
      - id: cleanup_gemini_policies
        name: Clean up Gemini policies before checking in
        language: system
        files: .gemini/policies/auto-saved.toml
        entry: cleanup_gemini_policies
      - id: luac
        name: Run `luac` if it's installed
        language: system
        types: [lua]
        entry: run-if-exists luac -p
      - id: luacheck
        name: Run `luacheck` if it's installed
        language: system
        types: [lua]
        # Ideally this would use the same args as
        # .config/nvim/lua/plugins/lint.lua does.
        entry: run-if-exists luacheck --globals vim table.unpack --std +lua51 --std +busted --codes --ranges
      - id: sort-spell-file
        name: Sort vim's spell file.
        language: system
        files: .config/nvim/spell/en.utf-8.add
        pass_filenames: false
        entry: sort -o .config/nvim/spell/en.utf-8.add .config/nvim/spell/en.utf-8.add
      - id: tools-test
        name: Run tests for tools.lua
        language: system
        entry: ./.config/nvim/lua/johntobin/tools_test.sh
        files: .config/nvim/lua/johntobin/tools*
      # keep-sorted end
