# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      # keep-sorted start
      - id: cleanup_gemini_policies
        name: Clean up Gemini policies before checking in
        language: system
        files: .gemini/policies/auto-saved.toml
        entry: cleanup_gemini_policies
      - id: keep-sorted
        name: Run `keep-sorted`
        language: system
        entry: run-if-exists keep-sorted
      - id: luac
        name: Run `luac` if it's installed
        language: system
        types: [lua]
        entry: run-if-exists luac -p
      - id: luacheck
        name: Run `luacheck` if it's installed
        language: system
        types: [lua]
        # Ideally this would use the same args as
        # .config/nvim/lua/plugins/lint.lua does.
        entry: run-if-exists luacheck --globals vim table.unpack --std +lua51 --std +busted --codes --ranges
      - id: shellcheck
        name: Run `shellcheck`
        language: system
        types: [shell]
        entry: shellcheck -e SC1090 -e SC1091
      - id: sort-spell-file
        name: Sort vim's spell file.
        language: system
        files: .config/nvim/spell/en.utf-8.add
        pass_filenames: false
        entry: sort -o .config/nvim/spell/en.utf-8.add .config/nvim/spell/en.utf-8.add
      - id: tools-test
        name: Run tests for tools.lua
        language: system
        entry: ./.config/nvim/lua/johntobin/tools_test.sh
        files: .config/nvim/lua/johntobin/tools*
      # keep-sorted end
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
