MinAlertLevel = suggestion

Packages = Google, proselint, write-good, Hugo

[*.{md}]
# ^ This section applies to only Markdown files.
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale, Google, proselint, write-good

# Disabling rules that are enabled by default.
# Far too aggressive about words like "was", "were", "it's", and many more.
write-good.E-Prime = NO
# Objects to every usage of "I", which doesn't work for my blog.
Google.FirstPerson = NO
