MinAlertLevel = suggestion

Packages = Google, proselint, write-good, Hugo

# Use word lists copied from Neovim.
# ~/.local/share/vale/styles/config/vocabularies/Neovim/
Vocab = Neovim

[*.{md}]
# ^ This section applies to only Markdown files.
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale, Google, proselint, write-good

# Disabling rules that are enabled by default.
# keep-sorted start
# Warns about literally every acronym.
Google.Acronyms = NO
# This complains about every uppercase letter after a colon.
Google.Colons = NO
# Objects to every usage of "I", which doesn't work for my blog.
Google.FirstPerson = NO
# If I'm not using `sentence-style capitalisation` I have a good reason for it.
Google.Headings = NO
# There's nothing wrong with using `e.g.`.
Google.Latin = NO
# Complains about *every* usage of parentheses.
Google.Parens = NO
# Too verbose.
Google.Passive = NO
# It complains about every use of "we".
Google.We = NO
# It complains about every use of "will".
Google.Will = NO
# You can't have case variations with this enabled, e.g. Bigtable and bigtable.
Vale.Terms = NO
# Far too aggressive about words like "was", "were", "it's", and many more.
write-good.E-Prime = NO
# Too verbose.
write-good.Passive = NO
# keep-sorted end
